name: RSpec
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1.0"
      - name: List all files
        run: ls && ruby -v
      - name: prepare DB
        run: rails db:prepare
