name: RSpec
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Install ruby 3.1.0
        run: |
          sudo apt-get install software-properties-common
          sudo apt-add-repository -y ppa:rael-gc/rvm
          sudo apt-get update
          sudo apt-get install rvm
          source /etc/profile.d/rvm.sh
          sudo usermod -a -G rvm $USER
          rvm install 3.1.0
          ruby -v
      - name: Install Rails
        run: |
          source /etc/profile.d/rvm.sh
          ruby -v
          rvm use 3.1.0
          sudo gem install railties -v 7.0.1
          sudo gem install bundler
          rails -v
      - name: List all files
        run: ls
      - name: prepare DB
        run: rails db:prepare
